### ISSUE TITLE
How to train the model on Pubmed summarization dataset?

### ISSUE THREAD

**Issue by Jiang-Xian** [neulab/guided_summarization#8]
Thank you for sharing your code. I notice that "max_pos" in "bert/train.sh" is set to 512, is it enough for Pubmed? Could you tell me how to train the model on Pubmed?

**Comment by zdou0830** [comment]
Thanks for the interest! 512 is enough for Pubmed and I didn't change this parameter if I remembered correctly. The training command should be the same with "bert/train.sh" but the min/max lengths of "bert/test.sh" should be different since the average length of the summaries in Pubmed is much longer than that in CNN/DM. (I think I set the min/max lengths to around 200/1000 during test for Pubmed but I cannot find the details right now.)

**Comment by Jiang-Xian** [comment]
Thank you!
